import pygame

# COLORS
WHITE = 255, 255, 255
BLACK = 0, 0, 0
DARK_GREY = 33, 33, 33
GREY = 127, 127, 127
LIGTH_GREY = 192, 192, 192
BACKGROUND_COLOR = BLACK
GRID_COLOR = DARK_GREY
APPLE_COLOR1 = 255, 127, 127
APPLE_COLOR2 = 255, 66, 66

# SETTINGS - KEYS
KEY_EXIT = pygame.K_ESCAPE
KEY_UP = pygame.K_UP
KEY_DOWN = pygame.K_DOWN
KEY_LEFT = pygame.K_LEFT
KEY_RIGHT = pygame.K_RIGHT
KEY_RESPAWN = pygame.K_r

# SETTINGS - GAME
GAME_NAME = "pysnake"
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = (640, 480)
CELL_SIZE = 20
COLUMNS, ROWS = int(SCREEN_WIDTH / CELL_SIZE), int(SCREEN_HEIGHT/CELL_SIZE)
FPS = 60
UP, DOWN, LEFT,RIGHT = ((0, -1), (0, 1),
                        (-1, 0), (1, 0))
OUT = -1

# SNAKE DEAFAULT SETTINGS
SNAKE_COLOR_SKIN = 33, 255, 33
SNAKE_COLOR_BODY = 33, 192, 33
SNAKE_COLOR_HEAD = 192, 192, 33
SNAKE_COLOR_SKIN_DEAD = LIGTH_GREY
SNAKE_COLOR_BODY_DEAD = GREY
SNAKE_COLOR_HEAD_DEAD = DARK_GREY
SNAKE_DEFAULT_X = 0
SNAKE_DEFAULT_Y = 0
SNAKE_DEFAULT_LENGTH = 5
SNAKE_DEFAULT_DIRECTION = RIGHT
SNAKE_DEFAULT_SPEED = 10
SNAKE_DEFAULT_LIVE = 100

